name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  collection: ^1.19.1
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  equatable: ^2.0.7
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  fl_chart: ^1.1.1
  fluentui_system_icons: ^1.1.273
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_slidable: ^4.0.3
  flutter_svg: ^2.2.0
  font_awesome_flutter: ^10.8.0
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  google_sign_in: ^7.1.1
  google_sign_in_android: ^7.0.3
  hugeicons: ^1.1.1
  image_picker: ^1.2.0
  intl: ^0.20.2
  ionicons: ^0.2.2
  jwt_decoder: ^2.0.1
  logger: ^2.6.1
  logging: ^1.3.0
  otp_timer_button: ^1.1.1
  pinput: ^5.0.1
  qr_code_scanner_plus: ^2.0.13
  qr_code_tools: ^0.2.0
  riverpod_annotation: ^2.6.1
  syncfusion_flutter_sliders: ^31.2.5
  web_socket_channel: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/splash.png
    - lib/assets/images/login.png
    - lib/assets/images/success_signup.png
    - lib/assets/images/reset_your_password.png
    - lib/assets/images/create_new_password.png
    - lib/assets/images/logo_hydros.png
    - lib/assets/images/home_top.png
    - lib/assets/images/no_plant_add.png
    - lib/assets/icons/google.svg
    - .env
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900